name: Kmer Speed Test [Rust]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "rust/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-rust.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "rust/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-rust.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Rust"
      lang: "rust"
