name: Kmer Speed Test [Haskell]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "haskell/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-haskell.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "haskell/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-haskell.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Haskell"
      lang: "haskell"
