name: Kmer Speed Test [PHP]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "php/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-php.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "php/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-php.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "PHP"
      lang: "php"
      kmer_values: "[11,12,13,14,15,16]"
