name: Kmer Speed Test [Java]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "java/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-java.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "java/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-java.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Java"
      lang: "java"
