name: Kmer Speed Test [Perl]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "perl/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-perl.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "perl/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-perl.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Perl"
      lang: "perl"
