name: Kmer Speed Test [C++]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "cpp/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-cpp.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "cpp/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-cpp.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "C++"
      lang: "cpp"
