name: Kmer Speed Test [C#]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "csharp/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-csharp.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "csharp/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-csharp.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "C#"
      lang: "csharp"
      setup_dotnet_version: "7.x"
