name: Kmer Speed Test [Go]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "go/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-go.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "go/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-go.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Go"
      lang: "go"
