name: Kmer Speed Test [Python]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "python/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-python.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "python/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-python.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Python"
      lang: "python"
