name: Kmer Speed Test [Lua]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "lua/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-lua.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "lua/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-lua.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Lua"
      lang: "lua"
      setup_command: "sudo apt-get update && sudo apt-get install -y luajit"
