name: Kmer Speed Test [JavaScript]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "js/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-js.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "js/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-js.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "JavaScript"
      lang: "js"
      setup_node_version: "19"
