name: Kmer Speed Test [Erlang]

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "erlang/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-erlang.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "erlang/**"
      - "Makefile"
      - ".github/workflows/_speed-test-reusable.yml"
      - ".github/workflows/speed-test-erlang.yml"

permissions:
  contents: read

jobs:
  kmer:
    uses: ./.github/workflows/_speed-test-reusable.yml
    with:
      display: "Erlang"
      lang: "erlang"
